dist: xenial
language: rust
cache: cargo

rust:
  - stable
  - nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install libfuse-dev

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo run -- --version
