[package]
name = "rrg"
description = "Rust rewrite of GRR."
version = "0.1.0"
authors = ["Łukasz Hanuszczak <hanuszczak@google.com>"]
edition = "2018"

[dependencies]
fleetspeak = { version = "0.1.1" }
humantime = { version = "2.0.0" }
log = { version = "0.4.8" }
proc-mounts = { version = "0.2.4" }
prost = { version = "0.6.1" }
prost-types = { version = "0.6.1" }
rrg-proto = { path = "proto/" }
simplelog = { version = "0.7.6" }
structopt = { version = "0.3.12" }
sys-info = { version = "0.5.1" }

[dev-dependencies]
tempfile = { version = "3.1.0" }

[target.'cfg(target_os = "linux")'.dev-dependencies]
fuse = { version = "0.3.1" }
users = { version = "0.10.0" }
